version: 2
jobs:
  build-job:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      # run tests!
      - run: mvn test
  deploy-job:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - run:
          name: Deploy Master to Google Cloud Platform
          command: mvn appengine:update
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master