version: 2
jobs:
  build-job:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          name: Resolve dependencies
          command: mvn dependency:go-offline
      - run: 
          name: Compile code
          command: mvn compile
  test-job:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          name: Resolve dependencies
          command: mvn dependency:go-offline
      - run: 
          name: Run tests
          command: mvn test
  deploy-job:
    docker: 
      - image: mrsvan/google-cloud-sdk-app-engine-java:jdk8-latest
    steps:
      - checkout
      - run: 
          name: Resolve dependencies
          command: mvn dependency:go-offline
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > $GCLOUD_KEY_FILE
      - run:
          name: Activate GCP credentials
          command: gcloud auth activate-service-account --key-file=$GCLOUD_KEY_FILE --project=$GOOGLE_PROJECT_ID
      - run:
          name: Deploy master to GCP
          command: mvn appengine:update -Dappengine.additionalParams="--service_account_json_key_file=$GCLOUD_KEY_FILE"
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-job
      - test-job:
          requires:
            -  build-job
      - deploy-job:
          requires:
            - test-job
          filters:
            branches:
              only: master
