version: 2
jobs:
  build-job:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: 
          name: Resolve dependencies
          command: mvn dependency:go-offline
      - run: 
          name: Compile code
          command: mvn compile
  test-job:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: 
          name: Resolve dependencies
          command: mvn dependency:go-offline
      - run: 
          name: Run tests
          command: mvn test
  deploy-job:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: 
          name: Resolve dependencies
          command: mvn dependency:go-offline
      - run:
          name: Deploy Master to Google Cloud Platform
          command: mvn appengine:update
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-job
      - test-job:
          requires:
            -  build-job
      - deploy-job:
          requires:
            - test-job
          filters:
            branches:
              only: master